export const extraQuestions = {
  maths: [
    { q: "Combien font 8 × 5 ?", a: "40", help: "8 groupes de 5." },
    { q: "Combien font 9 × 4 ?", a: "36", help: "Additionne 9 quatre fois." },
    { q: "Combien font 6 × 7 ?", a: "42", help: "Utilise la table de 6." },
    { q: "Combien font 12 × 3 ?", a: "36", help: "12 + 12 + 12." },
    { q: "Quelle est la moitié de 80 ?", a: "40", help: "Divise 80 par 2." },
    { q: "Combien font 100 - 37 ?", a: "63", help: "Retire 37 à 100." },
    { q: "Combien font 25 + 38 ?", a: "63", help: "Additionne les dizaines puis les unités." },
    { q: "Combien font 5 × 9 + 3 ?", a: "48", help: "Commence par la multiplication." },
    { q: "Combien font 144 ÷ 12 ?", a: "12", help: "12 × 12 = 144." },
    { q: "Combien font 3 × (4 + 2) ?", a: "18", help: "Calcule d'abord la parenthèse." },
    { q: "Quel est le double de 35 ?", a: "70", help: "35 + 35." },
    { q: "Combien font 250 + 175 ?", a: "425", help: "Additionne les centaines, dizaines et unités." },
    { q: "Combien font 90 ÷ 9 ?", a: "10", help: "9 × 10 = 90." },
    { q: "Combien font 11 × 11 ?", a: "121", help: "Utilise la table de 11." },
    { q: "Combien font 72 - 28 ?", a: "44", help: "Soustrais 20 puis 8." },
    { q: "Combien font 6 + 4 × 3 ?", a: "18", help: "Fais la multiplication avant l'addition." },
    { q: "7 × combien = 56 ?", a: "8", help: "Cherche dans la table de 7." },
    { q: "Combien font les trois quarts de 20 ?", a: "15", help: "Un quart de 20 vaut 5." }
  ],

  francais: [
    { q: "Quel est le pluriel de cheval ?", a: "chevaux", help: "Le pluriel est irrégulier." },
    { q: "Quel est le contraire de rapide ?", a: "lent", help: "Pense à quelqu'un qui avance doucement." },
    { q: "Quel est le féminin de petit ?", a: "petite", help: "Ajoute un e." },
    { q: "Quel est le verbe : « Marie regarde la télévision » ?", a: "regarde", help: "Cherche l'action." },
    { q: "Complète : Nous ___ à l'école. Verbe aller.", a: "allons", help: "Nous allons." },
    { q: "Quel est le sujet : « Mon frère joue au ballon » ?", a: "mon frère", help: "Qui joue ?" },
    { q: "Quel est le pluriel de journal ?", a: "journaux", help: "Le pluriel se termine par aux." },
    { q: "Quel est le contraire de chaud ?", a: "froid", help: "Pense à la glace." },
    { q: "Complète : Tu ___ un livre. Verbe lire.", a: "lis", help: "Tu lis." },
    { q: "Quel est l'adjectif dans « une grande maison » ?", a: "grande", help: "Il décrit la maison." },
    { q: "Quel est le nom dans « Le chat dort » ?", a: "chat", help: "C'est un animal." },
    { q: "Quel est le pluriel de bateau ?", a: "bateaux", help: "Ajoute x après eau." },
    { q: "Quel est le féminin de heureux ?", a: "heureuse", help: "Le féminin se termine par euse." },
    { q: "Complète : Ils ___ au parc. Verbe jouer.", a: "jouent", help: "Ils jouent." },
    { q: "Quel est l'infinitif de « nous finissons » ?", a: "finir", help: "Le verbe appartient au deuxième groupe." },
    { q: "Quel est le contraire de facile ?", a: "difficile", help: "Quelque chose de compliqué." },
    { q: "Quel pronom remplace « la table » ?", a: "elle", help: "Table est féminin." },
    { q: "Complète : J'___ une sœur. Verbe avoir.", a: "ai", help: "J'ai." }
  ],

  histoire: [
    { q: "Quelle est la capitale de la France ?", a: "paris", help: "C'est la plus grande ville française." },
    { q: "Dans quel pays se trouve Rome ?", a: "italie", help: "Rome est la capitale de ce pays." },
    { q: "Quelle est la capitale de l'Espagne ?", a: "madrid", help: "Elle se trouve au centre de l'Espagne." },
    { q: "Sur quel continent se trouve la France ?", a: "europe", help: "La France est un pays européen." },
    { q: "Quel océan se trouve à l'ouest de la France ?", a: "atlantique", help: "Il borde la côte ouest." },
    { q: "Quelle période vient après le Moyen Âge ?", a: "époque moderne", help: "Elle précède l'époque contemporaine." },
    { q: "Quelle est la capitale du Royaume-Uni ?", a: "londres", help: "La ville est traversée par la Tamise." },
    { q: "Sur quel continent se trouve l'Égypte ?", a: "afrique", help: "L'Égypte est au nord-est de ce continent." },
    { q: "Quelle est la capitale de l'Italie ?", a: "rome", help: "C'est une ville très ancienne." },
    { q: "Quelle mer borde le sud de la France ?", a: "méditerranée", help: "Elle borde aussi l'Espagne et l'Italie." },
    { q: "Quel fleuve traverse Paris ?", a: "seine", help: "Il traverse la capitale française." },
    { q: "Quelle est la capitale de l'Allemagne ?", a: "berlin", help: "C'est la plus grande ville allemande." },
    { q: "Quelle est la capitale du Portugal ?", a: "lisbonne", help: "Elle est proche de l'océan Atlantique." },
    { q: "Comment appelle-t-on les habitants de la France ?", a: "français", help: "C'est aussi le nom de la langue." },
    { q: "Quel continent se trouve au sud de l'Europe ?", a: "afrique", help: "La Méditerranée les sépare." },
    { q: "Quelle est la capitale du Japon ?", a: "tokyo", help: "C'est une immense ville japonaise." },
    { q: "Dans quel pays se trouve Barcelone ?", a: "espagne", help: "La ville est en Catalogne." },
    { q: "Quelle période vient après l'époque moderne ?", a: "époque contemporaine", help: "C'est la période la plus récente." }
  ],

  sciences: [
    { q: "Quel organe nous permet principalement de respirer ?", a: "poumons", help: "Ils se trouvent dans la poitrine." },
    { q: "Quel organe fait circuler le sang ?", a: "coeur", help: "Il bat continuellement." },
    { q: "Quelle étoile éclaire la Terre ?", a: "soleil", help: "Elle nous apporte lumière et chaleur." },
    { q: "Le dauphin est-il un poisson ou un mammifère ?", a: "mammifère", help: "Il respire avec des poumons." },
    { q: "Comment appelle-t-on le passage de l'eau liquide à la glace ?", a: "solidification", help: "L'eau devient solide." },
    { q: "Quel gaz est indispensable à notre respiration ?", a: "dioxygène", help: "Il est présent dans l'air." },
    { q: "Quelle est l'étoile la plus proche de la Terre ?", a: "soleil", help: "C'est notre étoile." },
    { q: "Combien de pattes possède un insecte ?", a: "6", help: "Trois paires de pattes." },
    { q: "Quel est l'état de l'eau du robinet ?", a: "liquide", help: "Elle prend la forme du récipient." },
    { q: "Comment appelle-t-on le passage de la glace à l'eau liquide ?", a: "fusion", help: "La glace fond." },
    { q: "Quel organe reçoit les aliments après l'œsophage ?", a: "estomac", help: "Il participe à la digestion." },
    { q: "Quels organes filtrent le sang et produisent l'urine ?", a: "reins", help: "Nous en avons normalement deux." },
    { q: "Comment appelle-t-on un animal qui mange seulement des végétaux ?", a: "herbivore", help: "Herbe donne un indice." },
    { q: "Quel est le satellite naturel de la Terre ?", a: "lune", help: "On peut l'observer la nuit." },
    { q: "Comment appelle-t-on le passage de l'eau liquide en vapeur ?", a: "vaporisation", help: "L'eau devient un gaz." },
    { q: "Quel sens est associé aux oreilles ?", a: "ouïe", help: "Il permet d'entendre." },
    { q: "Quel sens est associé aux yeux ?", a: "vue", help: "Il permet de voir." },
    { q: "Quel groupe d'animaux possède des plumes ?", a: "oiseaux", help: "Ils ont des ailes et des plumes." }
  ],

  anglais: [
    { q: "Comment dit-on « chat » en anglais ?", a: "cat", help: "Le mot commence par c." },
    { q: "Comment dit-on « chien » en anglais ?", a: "dog", help: "Trois lettres." },
    { q: "Que signifie « blue » ?", a: "bleu", help: "C'est une couleur." },
    { q: "Comment dit-on « merci » en anglais ?", a: "thank you", help: "Une formule de politesse." },
    { q: "Que signifie « school » ?", a: "école", help: "C'est l'endroit où l'on apprend." },
    { q: "Complète : She ___ happy.", a: "is", help: "Avec she, utilise is." },
    { q: "Que signifie « house » ?", a: "maison", help: "Un endroit où l'on habite." },
    { q: "Comment dit-on « livre » en anglais ?", a: "book", help: "Quatre lettres." },
    { q: "Que signifie « red » ?", a: "rouge", help: "C'est une couleur." },
    { q: "Comment dit-on « eau » en anglais ?", a: "water", help: "On en boit." },
    { q: "Que signifie « friend » ?", a: "ami", help: "Une personne que l'on apprécie." },
    { q: "Complète : You ___ my friend.", a: "are", help: "Avec you, utilise are." },
    { q: "Comment dit-on « soleil » en anglais ?", a: "sun", help: "Trois lettres." },
    { q: "Que signifie « morning » ?", a: "matin", help: "C'est le début de la journée." },
    { q: "Comment dit-on « mère » en anglais ?", a: "mother", help: "Le mot commence par m." },
    { q: "Que signifie « green » ?", a: "vert", help: "C'est une couleur." },
    { q: "Comment dit-on « école » en anglais ?", a: "school", help: "On y va pour apprendre." },
    { q: "Que signifie « goodbye » ?", a: "au revoir", help: "On le dit lorsqu'on part." }
  ],

  methode: [
    { q: "Vaut-il mieux relire la consigne avant de répondre ? (oui/non)", a: "oui", help: "Cela évite les erreurs de compréhension." },
    { q: "Faut-il tout apprendre seulement la veille ? (oui/non)", a: "non", help: "Il vaut mieux réviser régulièrement." },
    { q: "Les petites pauses sont-elles utiles ? (oui/non)", a: "oui", help: "Elles permettent de rester concentré." },
    { q: "Faut-il lire toute la consigne avant de commencer ? (oui/non)", a: "oui", help: "Lis-la jusqu'au bout." },
    { q: "Corriger ses erreurs aide-t-il à progresser ? (oui/non)", a: "oui", help: "Comprendre ses erreurs permet de progresser." },
    { q: "Est-il utile de revoir une leçon plusieurs fois ? (oui/non)", a: "oui", help: "La répétition aide la mémoire." },
    { q: "Faut-il limiter les distractions pendant les devoirs ? (oui/non)", a: "oui", help: "Cela améliore la concentration." },
    { q: "Expliquer une leçon avec ses propres mots est-il utile ? (oui/non)", a: "oui", help: "Cela vérifie que tu as compris." },
    { q: "Faire un planning de révision est-il utile ? (oui/non)", a: "oui", help: "Il aide à organiser son travail." },
    { q: "Faut-il abandonner immédiatement si un exercice est difficile ? (oui/non)", a: "non", help: "Essaie une méthode ou demande une explication." },
    { q: "Faut-il surligner uniquement les idées importantes ? (oui/non)", a: "oui", help: "Trop surligner n'aide pas à repérer l'essentiel." },
    { q: "Se tester sans regarder son cours aide-t-il à mémoriser ? (oui/non)", a: "oui", help: "Cela entraîne la mémoire." },
    { q: "Faut-il comprendre avant de mémoriser ? (oui/non)", a: "oui", help: "Comprendre facilite l'apprentissage." },
    { q: "Faut-il vérifier ses réponses avant de rendre un devoir ? (oui/non)", a: "oui", help: "Une relecture permet de repérer des erreurs." },
    { q: "Un endroit calme aide-t-il à travailler ? (oui/non)", a: "oui", help: "Il facilite la concentration." },
    { q: "Faut-il chercher un mot de consigne que l'on ne comprend pas ? (oui/non)", a: "oui", help: "Il faut comprendre ce qui est demandé." },
    { q: "Dormir suffisamment aide-t-il la mémoire ? (oui/non)", a: "oui", help: "Le sommeil participe à la mémorisation." },
    { q: "Faut-il revoir les questions ratées après un quiz ? (oui/non)", a: "oui", help: "C'est une bonne façon de progresser." }
  ]
};
