"use client";

import { useEffect, useMemo, useState } from "react";
import { extraQuestions } from "./extraQuestions";
const levels = ["CP", "CE1", "CE2", "CM1", "CM2", "6e", "5e", "4e", "3e"];
const subjects = [
  { id:"maths", icon:"＋", name:"Mathématiques", color:"blue", intro:"Multiplier, c’est additionner plusieurs fois le même nombre.", example:"3 × 5 signifie 5 + 5 + 5. Le résultat est 15.", tip:"Dessine les groupes si le calcul te paraît difficile.", questions:[
    {q:"Combien font 4 × 6 ?",a:"24",help:"Additionne 6 quatre fois."},{q:"Combien font 7 × 3 ?",a:"21",help:"Pense à la table de 3."},{q:"Combien font 8 × 5 ?",a:"40",help:"Pense à la table de 5."},{q:"Combien font 9 × 4 ?",a:"36",help:"4 × 10 = 40, puis enlève 4."},{q:"Combien font 6 × 7 ?",a:"42",help:"Pense à la table de 7."},{q:"Combien font 12 × 3 ?",a:"36",help:"12 + 12 + 12."},{q:"Quelle est la moitié de 80 ?",a:"40",help:"Partage 80 en deux."},{q:"Combien font 100 - 37 ?",a:"63",help:"Retire 30 puis 7."},{q:"Combien font 25 + 38 ?",a:"63",help:"25 + 30 puis + 8."},{q:"Combien font 5 × 9 + 3 ?",a:"48",help:"Calcule d’abord 5 × 9."}]},
  { id:"francais", icon:"A", name:"Français", color:"red", intro:"Le sujet indique qui fait l’action. Le verbe indique l’action.", example:"Dans « Lina prépare son cartable », Lina est le sujet et prépare est le verbe.", tip:"Pour trouver le verbe, demande-toi : que fait le sujet ?", questions:[
    {q:"Quel est le verbe : « Paul mange une pomme » ?",a:"mange",help:"Cherche l’action de Paul."},{q:"Quel est le sujet : « Les élèves travaillent » ?",a:"les élèves",help:"Qui travaille ?"},{q:"Quel est le pluriel de « chat » ?",a:"chats",help:"Ajoute un s."},{q:"Quel est le contraire de « grand » ?",a:"petit",help:"Cherche le mot opposé."},{q:"Complète : Nous ___ à l’école. (aller)",a:"allons",help:"Conjugue aller avec nous."},{q:"Quel est le verbe : « Marie lit un livre » ?",a:"lit",help:"Que fait Marie ?"},{q:"Quel est le sujet : « Le chien court vite » ?",a:"le chien",help:"Qui court ?"},{q:"Quel est le pluriel de « maison » ?",a:"maisons",help:"Ajoute un s."},{q:"Quel est le contraire de « chaud » ?",a:"froid",help:"Pense à la température opposée."},{q:"Complète : Ils ___ au ballon. (jouer)",a:"jouent",help:"Conjugue jouer avec ils."}]},
  { id:"histoire", icon:"⌛", name:"Histoire-Géo", color:"amber", intro:"Une frise chronologique place les événements du plus ancien au plus récent.", example:"L’Antiquité vient avant le Moyen Âge, qui vient avant l’époque moderne.", tip:"Lis toujours une frise de gauche à droite.", questions:[
    {q:"Quelle période vient après l’Antiquité ?",a:"moyen âge",help:"La période des châteaux forts."},{q:"Dans quel pays se trouve Paris ?",a:"france",help:"Paris en est la capitale."},{q:"Quelle est la capitale de la France ?",a:"paris",help:"C’est la capitale française."},{q:"Sur quel continent se trouve la France ?",a:"europe",help:"La France est un pays européen."},{q:"Quelle période vient après le Moyen Âge ?",a:"époque moderne",help:"Elle précède l’époque contemporaine."},{q:"Quelle est la capitale de l’Italie ?",a:"rome",help:"Ville célèbre de l’Antiquité."},{q:"Quel océan est à l’ouest de la France ?",a:"atlantique",help:"Pense à la côte ouest."},{q:"Sur quel continent se trouve l’Égypte ?",a:"afrique",help:"Au nord-est de ce continent."},{q:"Quelle est la capitale de l’Espagne ?",a:"madrid",help:"Elle est au centre de l’Espagne."},{q:"Quelle période vivons-nous aujourd’hui ?",a:"époque contemporaine",help:"La période la plus récente."}]},
  { id:"sciences", icon:"⚗", name:"Sciences", color:"green", intro:"L’eau existe sous trois états : solide, liquide et gazeux.", example:"La glace est solide, l’eau du robinet est liquide et la vapeur est gazeuse.", tip:"Un changement de température peut faire changer l’état de l’eau.", questions:[
    {q:"Quel est l’état de la glace ?",a:"solide",help:"Elle garde sa forme."},{q:"Comment appelle-t-on l’eau sous forme de gaz ?",a:"vapeur",help:"Au-dessus d’une casserole chaude."},{q:"Quel organe permet principalement de respirer ?",a:"poumons",help:"Ils sont dans la poitrine."},{q:"Quel organe fait circuler le sang ?",a:"coeur",help:"Il bat dans la poitrine."},{q:"Quelle étoile éclaire la Terre ?",a:"soleil",help:"On la voit le jour."},{q:"Le dauphin est-il un poisson ou un mammifère ?",a:"mammifère",help:"Il respire avec des poumons."},{q:"Passage de l’eau liquide à la glace ?",a:"solidification",help:"L’eau devient solide."},{q:"Quel gaz est indispensable à notre respiration ?",a:"dioxygène",help:"On l’appelle aussi oxygène."},{q:"Combien de pattes possède un insecte ?",a:"6",help:"Trois paires."},{q:"Quel est l’état de l’eau dans un verre ?",a:"liquide",help:"Elle prend la forme du récipient."}]},
  { id:"anglais", icon:"EN", name:"Anglais", color:"purple", intro:"Le verbe « to be » permet de dire qui l’on est ou comment on se sent.", example:"I am = je suis. You are = tu es. He or she is = il ou elle est.", tip:"Répète les phrases à voix haute pour mieux les mémoriser.", questions:[
    {q:"Complète : I ___ happy.",a:"am",help:"Avec I : am."},{q:"Que signifie « hello » ?",a:"bonjour",help:"Une formule pour saluer."},{q:"Que signifie « cat » ?",a:"chat",help:"Un animal domestique."},{q:"Que signifie « dog » ?",a:"chien",help:"Un animal domestique."},{q:"Que signifie « blue » ?",a:"bleu",help:"Une couleur."},{q:"Que signifie « thank you » ?",a:"merci",help:"Pour remercier."},{q:"Que signifie « school » ?",a:"école",help:"L’endroit où l’on apprend."},{q:"Complète : She ___ happy.",a:"is",help:"Avec she : is."},{q:"Que signifie « house » ?",a:"maison",help:"Un lieu où l’on habite."},{q:"Que signifie « book » ?",a:"livre",help:"On peut le lire."}]},
  { id:"methode", icon:"✎", name:"Méthodologie", color:"cyan", intro:"Une séance courte et régulière est plus efficace qu’une longue séance au dernier moment.", example:"Lis 10 minutes, ferme le cours, puis explique avec tes propres mots.", tip:"Travaille 25 minutes, puis fais une pause de 5 minutes.", questions:[
    {q:"Après 25 minutes de travail, combien de minutes de pause ?",a:"5",help:"Une pause courte."},{q:"Vaut-il mieux réviser régulièrement ? (oui/non)",a:"oui",help:"Un peu chaque jour."},{q:"Faut-il lire toute la consigne ? (oui/non)",a:"oui",help:"Lis avant de répondre."},{q:"Vaut-il mieux tout apprendre la veille ? (oui/non)",a:"non",help:"Révise régulièrement."},{q:"Une courte pause aide-t-elle à rester concentré ? (oui/non)",a:"oui",help:"Elle permet de récupérer."},{q:"Faut-il comprendre ses erreurs ? (oui/non)",a:"oui",help:"Pour ne pas les refaire."},{q:"Répéter aide-t-il à mémoriser ? (oui/non)",a:"oui",help:"La répétition aide la mémoire."},{q:"Faut-il éloigner les distractions ? (oui/non)",a:"oui",help:"Pour mieux se concentrer."},{q:"Expliquer avec ses propres mots est-il utile ? (oui/non)",a:"oui",help:"Cela vérifie la compréhension."},{q:"Après une mauvaise réponse, faut-il abandonner ? (oui/non)",a:"non",help:"Comprends l’erreur et réessaie."}]}
];
subjects.forEach((subject) => {
  subject.questions.push(...(extraQuestions[subject.id] || []));
});
/*
MISE À JOUR RÉUSSITE+
- 10 questions par matière
- 6 matières = 60 exercices
Dans le page.js actuel, remplacer l'ancien bloc "const subjects = [...]" par celui-ci.
Puis remplacer:
const progress = Math.round((completed.length / 12) * 100);
par:
const totalExercises = subjects.reduce((total, subject) => total + subject.questions.length, 0);
const progress = Math.min(100, Math.round((completed.length / totalExercises) * 100));

Remplacer "sur 12" par "sur {totalExercises}"
et "1 cours · 2 exercices" par "1 cours · {s.questions.length} exercices".
*/
